### ISSUE TITLE
알고스팟 - FESTIVAL

### ISSUE THREAD

**Issue by singun** [lsj4401/algorithms#18]
https://www.algospot.com/judge/problem/read/FESTIVAL

**Comment by singun** [comment]
@lsj4401 `RTE (nonzero return code)` 이거랑 너무 친해 -ㅁ- ... 구글링해보니까 스택오버플로우 나도 저거 뜰 수 있다길래 경우의 수를 늘려서 해봤는데 .. 그래도 잘 모르겠음 ...

**Comment by singun** [comment]
@lsj4401 성주 근데 이슈 관리 할때, 보통은 자기 브랜치에서 작업하고 난 다음에 풀리퀘 보내면서 이슈 번호를 태깅 하나 ?

**Comment by lsj4401** [comment]
@singun 나도 잘 몰라 이슈로 관리해본게 없어서 
그냥 해당 이슈랑 관련있는거 모아보기 정도 생각하면 될거같은데 ? 
우리가 딱 적당하게 쓰고 있다고 생각함
