### ISSUE TITLE
넘버게임

### ISSUE THREAD

**Issue by lsj4401** [lsj4401/algorithms#22]
https://leetcode.com/problems/range-sum-query-immutable/

**Comment by lsj4401** [comment]
https://algospot.com/judge/problem/read/NUMBERGAME
사실은 이거

**Comment by lsj4401** [comment]
https://github.com/lsj4401/algorithms/tree/master/NUMBERGAME 코드는 여기에 올려주세요

**Comment by ChaeSW** [comment]
음....나름 늦은시간까지 머리를 써봐도....잘 모르겠구만 이건

**Comment by lsj4401** [comment]
@ChaeSW 고생하셨습니다
